name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Lightsail
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true

          script: |
            set -e

            export PATH=$PATH:/home/ubuntu/.npm-global/bin

            cd /home/ubuntu/louisianaroma-backend

            echo "=== PULLING CODE ==="
            git pull origin main

            echo "=== INSTALL ==="
            pnpm install

            echo "=== PRISMA ==="
            pnpm prisma generate

            echo "=== BUILD ==="
            pnpm build

            echo "=== PM2 RELOAD ==="
            pm2 reload louisiana-api || pm2 restart louisiana-api
